spring:
  application:
    name: fiap-auth-service-app

  mail:
    host: ${SPRING_MAIL_HOST:maildev}
    port: ${SPRING_MAIL_PORT:1025}
    protocol: smtp
    test-connection: true
    properties:
      mail:
        smtp:
          auth: false  # MailDev não requer autenticação
          starttls:
            enable: false  # TLS não é necessário para MailDev

  profiles:
    active: dev

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/fiap_auth_service_db}
    #    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/fiap_auth_service_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update  # Altere para 'update' se desejar que o Hibernate atualize o esquema automaticamente
    show-sql: true
    properties:
      hibernate:
        format_sql: true  # Opcional: formata o SQL no log
        use_sql_comments: true  # Opcional: adiciona comentários sobre as consultas
    open-in-view: false  # Desative caso queira evitar problemas de Lazy Initialization

server:
  port: 8081

#security:
#  user:
#    name: admin  # Usuário padrão para autenticação básica
#    password: admin  # Senha padrão para autenticação básica (substitua em produção)

#  jwt:
#    issuer: /fiap-auth-service-app/.well-known/openid-configuration
#    secret: admin123  #> admin # Substitua por sua chave secreta real em Base64
#    expiration: 3600 # Tempo de expiração do token (em segundos)
jwt:
  secret: pkaAJSvAscjFHe/eFbcXfkHZvTw/GgQKnSk7GS9Ug9v8CX6aY6MnyNe5hbprYedic1x3w6OvIV7jkBx9cXd6Tg==
  expiration: 3600000 # 1 hour

logging:
  level:
    root: INFO
    org.springframework: INFO
