apiVersion: v1
kind: Service
metadata:
  name: fiap-auth-service-app
  namespace: fiap-auth-service-app
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8082        # Porta do serviço no Kubernetes
      targetPort: 8082  # Porta interna do container
      nodePort: 30082   # Porta exposta na máquina host (para acesso externo)
  selector:
    app: fiap-auth-service-app
